-- MySQL Script generated by MySQL Workbench
-- Fri 15 Feb 2019 07:04:55 PM WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cabinet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cabinet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cabinet` ;
USE `cabinet` ;

-- -----------------------------------------------------
-- Table `cabinet`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Patient` (
  `idPatient` INT NOT NULL AUTO_INCREMENT,
  `nomPatient` VARCHAR(255) NULL,
  `prenomPatient` VARCHAR(255) NULL,
  `telephonePatient` VARCHAR(20) NULL,
  `mailPatient` VARCHAR(255) NULL,
  `dateNaissance` DATE NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Personnel` (
  `idPersonnel` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `telephone` VARCHAR(20) NULL,
  `mail` VARCHAR(255) NULL,
  PRIMARY KEY (`idPersonnel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Docteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Docteur` (
  `idDocteur` INT NOT NULL AUTO_INCREMENT,
  `specialite` VARCHAR(255) NULL,
  `Personnel_idPersonnel` INT NOT NULL,
  PRIMARY KEY (`idDocteur`),
  INDEX `fk_Docteur_Personnel1_idx` USING BTREE (`Personnel_idPersonnel`),
  CONSTRAINT `fk_Docteur_Personnel1`
    FOREIGN KEY (`Personnel_idPersonnel`)
    REFERENCES `cabinet`.`Personnel` (`idPersonnel`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Consultation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Consultation` (
  `idConsultation` INT NOT NULL AUTO_INCREMENT,
  `dateConsultation` DATE NULL,
  `fraisConsultation` VARCHAR(45) NULL,
  `Patient_idPatient` INT NOT NULL,
  `nomDocteur` VARCHAR(255) NOT NULL,
  `note` VARCHAR(255) NULL,
  PRIMARY KEY (`idConsultation`),
  INDEX `fk_Consultation_Patient1_idx` (`Patient_idPatient` ASC),
  CONSTRAINT `fk_Consultation_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `cabinet`.`Patient` (`idPatient`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Rdv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Rdv` (
  `idRdv` INT NOT NULL AUTO_INCREMENT,
  `dateJour` DATE NULL,
  `dateRdv` DATETIME NULL,
  `Patient_idPatient` INT NOT NULL,
  PRIMARY KEY (`idRdv`),
  INDEX `fk_Rdv_Patient1_idx` (`Patient_idPatient` ASC),
  CONSTRAINT `fk_Rdv_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `cabinet`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Paiement` (
  `idPaiement` INT NOT NULL AUTO_INCREMENT,
  `datePaiement` DATE NULL,
  `modePaiement` VARCHAR(255) NULL,
  `montant` DOUBLE NULL,
  `reste` VARCHAR(45) NULL,
  `Consultation_idConsultation` INT NOT NULL,
  PRIMARY KEY (`idPaiement`),
  INDEX `fk_Paiement_Consultation1_idx` (`Consultation_idConsultation` ASC),
  CONSTRAINT `fk_Paiement_Consultation1`
    FOREIGN KEY (`Consultation_idConsultation`)
    REFERENCES `cabinet`.`Consultation` (`idConsultation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Ordonnance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Ordonnance` (
  `idOrdonnance` INT NOT NULL AUTO_INCREMENT,
  `note` VARCHAR(45) NULL,
  `Consultation_idConsultation` INT NOT NULL,
  PRIMARY KEY (`idOrdonnance`),
  INDEX `fk_Ordonnance_Consultation1_idx` (`Consultation_idConsultation` ASC),
  CONSTRAINT `fk_Ordonnance_Consultation1`
    FOREIGN KEY (`Consultation_idConsultation`)
    REFERENCES `cabinet`.`Consultation` (`idConsultation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet`.`Acte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet`.`Acte` (
  `idActe` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  `noteActe` VARCHAR(255) NULL,
  `Consultation_idConsultation` INT NOT NULL,
  `dentActe` INT NULL,
  PRIMARY KEY (`idActe`),
  INDEX `fk_Acte_Consultation1_idx` (`Consultation_idConsultation` ASC),
  CONSTRAINT `fk_Acte_Consultation1`
    FOREIGN KEY (`Consultation_idConsultation`)
    REFERENCES `cabinet`.`Consultation` (`idConsultation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
